# Output directory
work_directory: 'results-iris/'

# Model parameters
model_name: "Model-42"
hpo_trials: 1000

# Input data
database: 'datasets/iris/data.tsv'
features_continuous: 'petal_length,petal_width,sepal_length,sepal_width'
features_categorical: ''
